### ISSUE TITLE
ReaderRIOTRDFXML (NoClassDefFoundError)

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.trs-client#12]
```
org.eclipse.lyo.oslc4j.trs.client.test.SparqlUtilTest  Time elapsed: 0.626 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/jena/riot/lang/ReaderRIOTRDFXML
	at org.apache.jena.tdb2.TDB2.init(TDB2.java:127)
	at org.apache.jena.tdb2.sys.InitTDB2.start(InitTDB2.java:28)
	at org.apache.jena.system.JenaSystem.lambda$init$40(JenaSystem.java:114)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:179)
	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:156)
	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:111)
	at org.apache.jena.tdb.TDBFactory.<clinit>(TDBFactory.java:40)
	at org.eclipse.lyo.oslc4j.trs.client.test.SparqlUtilTest.setUpBeforeClass(SparqlUtilTest.java:83)
```

**Comment by berezovskyi** [comment]
fixed in #11
